### ISSUE TITLE
How to get the config.title value in routes/fake-route.js ? 

### ISSUE THREAD

**Issue by kerphi** [Inist-CNRS/castor-boilerplate#3]
There is a template rendering on this line: 
https://github.com/Inist-CNRS/castor-boilerplate/blob/master/routes/fake-route.js#L12

I'd like to access the config.local.js "title" key (supposing it is the same as [config.sample.js](https://github.com/Inist-CNRS/castor-boilerplate/blob/master/config.sample.js)) and give it to the template just near the ``{name : "World"}``

**Comment by parmentf** [comment]
You'd have to use something like `config.get('title')`, but I think you have to get `config` first.
That depends on the file you're in.

**Comment by parmentf** [comment]
See [app/routes/table.js](https://github.com/castorjs/castor-core/blob/fd4c4ec05d8b18d30889dca5a38610da65b8ea7d/app/routes/table.js#L18-L19)

**Comment by kerphi** [comment]
Thank you.
But i have a last one :) https://github.com/Inist-CNRS/castor-boilerplate/commit/244b31c3607ffc5063f958440692aef3997bab15#commitcomment-16767170
